name: manage-azure-policy-e870fc3f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'seerene/policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**'
#      - 'seerene/policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**'
#      - 'seerene/policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**'
#      - 'seerene/policies/No_child_resources_in_Automation_Account_Deny-AA-child-resources/**'
#      - 'seerene/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**'
#      - 'seerene/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**'
#      - 'seerene/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**'
#      - 'seerene/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**'
#      - 'seerene/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**'
#      - 'seerene/policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**'
#      - 'seerene/policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**'
#      - 'seerene/policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**'
#      - 'seerene/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**'
#      - 'seerene/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**'
#      - 'seerene/policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**'
#      - 'seerene/policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
#      - 'seerene/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**'
#      - 'seerene/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
#      - 'seerene/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
#      - 'seerene/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**'
#      - 'seerene/policies/Deny_vNet_peering_cross_subscription_except_for_excluded_subscriptions._Deny-VNET-Peer-Cross-Sub-Except-Allowed/**'
#      - 'seerene/policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**'
#      - 'seerene/policies/Deploy_Network_Watcher_Extension_for_Linux_virtual_machines_Deploy-NW-VMExtension-Linux/**'
#      - 'seerene/policies/Deploy_Network_Watcher_Extension_on_Windows_virtual_machines_Deploy-NW-VMExtension-Windows/**'
#      - 'seerene/policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**'
#      - 'seerene/policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**'
#      - 'seerene/policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**'
#      - 'seerene/policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**'
#      - .github/workflows/manage-azure-policy-e870fc3f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e870fc3f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          seerene/policies/AppService_append_enable_https_only_setting_to_enforce_https_setting._Append-AppService-httpsonly/**
          seerene/policies/AppService_append_sites_with_minimum_TLS_version_to_enforce._Append-AppService-latestTLS/**
          seerene/policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**
          seerene/policies/No_child_resources_in_Automation_Account_Deny-AA-child-resources/**
          seerene/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**
          seerene/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**
          seerene/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**
          seerene/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**
          seerene/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**
          seerene/policies/Public_network_access_on_AKS_API_should_be_disabled_Deny-PublicEndpoint-Aks/**
          seerene/policies/Public_network_access_should_be_disabled_for_CosmosDB_Deny-PublicEndpoint-CosmosDB/**
          seerene/policies/Public_network_access_should_be_disabled_for_KeyVault_Deny-PublicEndpoint-KeyVault/**
          seerene/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**
          seerene/policies/Public_network_access_should_be_disabled_for_MySQL_Deny-PublicEndpoint-MySQL/**
          seerene/policies/Public_network_access_onStorage_accounts_should_be_disabled_Deny-PublicEndpoint-Storage/**
          seerene/policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          seerene/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**
          seerene/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          seerene/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          seerene/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**
          seerene/policies/Deny_vNet_peering_cross_subscription_except_for_excluded_subscriptions._Deny-VNET-Peer-Cross-Sub-Except-Allowed/**
          seerene/policies/Azure_Database_for_MySQL_server_deploy_a_specific_min_TLS_version_and_enforce_SSL._Deploy-MySQL-sslEnforcement/**
          seerene/policies/Deploy_Network_Watcher_Extension_for_Linux_virtual_machines_Deploy-NW-VMExtension-Linux/**
          seerene/policies/Deploy_Network_Watcher_Extension_on_Windows_virtual_machines_Deploy-NW-VMExtension-Windows/**
          seerene/policies/Azure_Database_for_PostgreSQL_server_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL_Deploy-PostgreSQL-sslEnforcement/**
          seerene/policies/SQL_servers_deploys_a_specific_min_TLS_version_requirement._Deploy-SQL-minTLS/**
          seerene/policies/SQL_managed_instances_deploy_a_specific_min_TLS_version_requirement._Deploy-SqlMi-minTLS/**
          seerene/policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**
